### ISSUE TITLE
pip install pyreaper failed(ARM)

### ISSUE THREAD

**Issue by Ting011** [r9y9/pyreaper#19]
## Environment
Jetson AGX Orin (ARM)
Ubuntu 20.04
conda python 3.8.17
cython 3.0.0

### Error brief
Things go wrong when I try to install pyreaper on my Jetson Orin device and fail in building wheel for pyreaper.
Also, same error happen on my personal x86 computer (Python 3.10.6 Ubuntu 22.04)

### What I have tried
```
pip install wheel
```
```
pip install --no-cache-dir pyreaper
```
```
sudo apt-get install libpcap-dev libpq-dev
```

Error log have been enclosed, any help or envidence will be appreciate. 

### Log
```
~$ pip install pyreaper
Collecting pyreaper
  Using cached pyreaper-0.0.9.tar.gz (59 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.8.0 in ./anaconda3/envs/face/lib/python3.8/site-packages (from pyreaper) (1.24.4)
Building wheels for collected packages: pyreaper
  Building wheel for pyreaper (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyreaper (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [461 lines of output]
      ['lib/REAPER/core/track.cc', 'lib/REAPER/core/file_resource.cc', 'lib/REAPER/core/float_matrix.cc', 'lib/REAPER/epoch_tracker/epoch_tracker.cc', 'lib/REAPER/epoch_tracker/lpc_analyzer.cc', 'lib/REAPER/epoch_tracker/fft.cc', 'lib/REAPER/epoch_tracker/fd_filter.cc']
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-38
      creating build/lib.linux-aarch64-cpython-38/pyreaper
      copying pyreaper/__init__.py -> build/lib.linux-aarch64-cpython-38/pyreaper
      running build_ext
      <string>:18: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      /tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-51545jft/pyreaper_b20dbdcaa1a9437ead875024c867204d/pyreaper/creaper.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from libcpp.vector cimport vector
      
      from libcpp.cast cimport reinterpret_cast
      from libc.stdint cimport int16_t, int32_t
      
      from reaper cimport reaper as _reaper
      ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:18:0: 'reaper.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from libcpp.vector cimport vector
      
      from libcpp.cast cimport reinterpret_cast
      from libc.stdint cimport int16_t, int32_t
      
      from reaper cimport reaper as _reaper
      ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:18:0: 'reaper/reaper.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from libc.stdint cimport int16_t, int32_t
      
      from reaper cimport reaper as _reaper
      
      cdef class Track:
          cdef _reaper.Track * ptr
               ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:21:9: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          .. note::
      
              This isn't intended to be used directly in general. Use wrapper function instead
              unless if you don't want to understand internals.
          """
          cdef _reaper.EpochTracker * ptr
               ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:51:9: 'EpochTracker' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                               vector[float] * times,
                               vector[int16_t] * voicing):
              self.ptr.GetFilledEpochs(unvoiced_pm_interval, times, voicing)
      
          # Convenient wrapper methods
          cdef GetEpochTrack(self, float inter_pulse, _reaper.Track * pm_track):
                                                      ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:96:48: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  ( & pm_track.t(i))[0] = times[i]
                  pm_track.set_v(i, voicing[i])
      
              return True
      
          cdef GetTrackVoicedFlags(self, _reaper.Track * track,
                                         ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:111:35: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                                   np.ndarray[np.int32_t, ndim = 1, mode = "c"] voiced_flags):
              cdef int32_t i
              for i in range(0, track.num_frames()):
                  voiced_flags[i] = 1 if track.v(i) else 0
      
          cdef GetTrackTimes(self, _reaper.Track * track, float * times):
                                   ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:117:29: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef GetTrackTimes(self, _reaper.Track * track, float * times):
              cdef int32_t i
              for i in range(0, track.num_frames()):
                  times[i] = track.t(i)
      
          cdef GetTrackValues(self, _reaper.Track * track, float * values):
                                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:122:30: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              cdef int32_t i
              for i in range(0, track.num_frames()):
                  values[i] = track.a(i)
      
          cdef GetF0AndCorrTrack(self, float external_frame_interval,
                                 _reaper.Track * f0_track,
                                 ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:128:27: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(0, track.num_frames()):
                  values[i] = track.a(i)
      
          cdef GetF0AndCorrTrack(self, float external_frame_interval,
                                 _reaper.Track * f0_track,
                                 _reaper.Track * corr_track):
                                 ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:129:27: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef class Track:
          cdef _reaper.Track * ptr
      
          def __cinit__(self):
              self.ptr = new _reaper.Track()
                             ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:24:23: 'Track' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef class Track:
          cdef _reaper.Track * ptr
      
          def __cinit__(self):
              self.ptr = new _reaper.Track()
                         ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:24:19: new operator can only be applied to a C++ class
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          def __cinit__(self):
              self.ptr = new _reaper.Track()
      
          def __dealloc__(self):
              del self.ptr
                      ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:27:16: Deletion of non-Python, non-C++ object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              unless if you don't want to understand internals.
          """
          cdef _reaper.EpochTracker * ptr
      
          def __cinit__(self):
              self.ptr = new _reaper.EpochTracker()
                             ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:54:23: 'EpochTracker' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              unless if you don't want to understand internals.
          """
          cdef _reaper.EpochTracker * ptr
      
          def __cinit__(self):
              self.ptr = new _reaper.EpochTracker()
                         ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:54:19: new operator can only be applied to a C++ class
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          def __cinit__(self):
              self.ptr = new _reaper.EpochTracker()
      
          def __dealloc__(self):
              del self.ptr
                      ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:57:16: Deletion of non-Python, non-C++ object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          def Init(self, np.ndarray[np.int16_t, ndim=1, mode="c"] input,
                   float sample_rate, float min_f0_search, float max_f0_search,
                   bool do_highpass, bool do_hilbert_transform):
              cdef int32_t n_input = len(input)
              return self.ptr.Init( & input[0], n_input, sample_rate, min_f0_search,
                                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:63:30: Cannot convert 'int16_t *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.ptr.set_unvoiced_cost(v)
      
          cdef ResampleAndReturnResults(self, float resample_interval,
                                        vector[float] * f0,
                                        vector[float] * correlations):
              return self.ptr.ResampleAndReturnResults(resample_interval, f0,
                                                                          ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:87:68: Cannot convert 'vector[float] *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef ResampleAndReturnResults(self, float resample_interval,
                                        vector[float] * f0,
                                        vector[float] * correlations):
              return self.ptr.ResampleAndReturnResults(resample_interval, f0,
                                                       correlations)
                                                       ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:88:49: Cannot convert 'vector[float] *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                                                       correlations)
      
          cdef GetFilledEpochs(self, float unvoiced_pm_interval,
                               vector[float] * times,
                               vector[int16_t] * voicing):
              self.ptr.GetFilledEpochs(unvoiced_pm_interval, times, voicing)
                                                             ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:93:55: Cannot convert 'vector[float] *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                                                       correlations)
      
          cdef GetFilledEpochs(self, float unvoiced_pm_interval,
                               vector[float] * times,
                               vector[int16_t] * voicing):
              self.ptr.GetFilledEpochs(unvoiced_pm_interval, times, voicing)
                                                                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:93:62: Cannot convert 'vector[int16_t] *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          # Convenient wrapper methods
          cdef GetEpochTrack(self, float inter_pulse, _reaper.Track * pm_track):
              cdef vector[float] times
              cdef vector[int16_t] voicing
      
              self.ptr.GetFilledEpochs(inter_pulse, & times, & voicing)
                                                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:100:46: Cannot convert 'vector[float] *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          # Convenient wrapper methods
          cdef GetEpochTrack(self, float inter_pulse, _reaper.Track * pm_track):
              cdef vector[float] times
              cdef vector[int16_t] voicing
      
              self.ptr.GetFilledEpochs(inter_pulse, & times, & voicing)
                                                             ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:100:55: Cannot convert 'vector[int16_t] *' to Python object
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              pm_track.resize(times.size(), 1)
      
              cdef int32_t i
              for i in range(0, times.size()):
                  ( & pm_track.t(i))[0] = times[i]
                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:106:14: Taking address of non-lvalue (type Python object)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              corr_track.resize(corr.size(), 1)
              cdef int32_t i
              cdef float t
              for i in range(0, f0.size()):
                  t = external_frame_interval * i
                  ( & f0_track.t(i))[0] = t
                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:142:14: Taking address of non-lvalue (type Python object)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              cdef int32_t i
              cdef float t
              for i in range(0, f0.size()):
                  t = external_frame_interval * i
                  ( & f0_track.t(i))[0] = t
                  ( & corr_track.t(i))[0] = t
                    ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:143:14: Taking address of non-lvalue (type Python object)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  t = external_frame_interval * i
                  ( & f0_track.t(i))[0] = t
                  ( & corr_track.t(i))[0] = t
                  f0_track.set_v(i, True if f0[i] > 0.0 else False)
                  corr_track.set_v(i, True if f0[i] > 0.0 else False)
                  (& f0_track.a(i))[0] = f0[i] if f0[i] > 0.0 else -1.0;
                   ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:146:13: Taking address of non-lvalue (type Python object)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  ( & f0_track.t(i))[0] = t
                  ( & corr_track.t(i))[0] = t
                  f0_track.set_v(i, True if f0[i] > 0.0 else False)
                  corr_track.set_v(i, True if f0[i] > 0.0 else False)
                  (& f0_track.a(i))[0] = f0[i] if f0[i] > 0.0 else -1.0;
                  (& corr_track.a(i))[0] = corr[i]
                   ^
      ------------------------------------------------------------
      
      pyreaper/creaper.pyx:147:13: Taking address of non-lvalue (type Python object)
      Compiling pyreaper/creaper.pyx because it changed.
      [1/1] Cythonizing pyreaper/creaper.pyx
      Traceback (most recent call last):
        File "/home/ubt/anaconda3/envs/face/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ubt/anaconda3/envs/face/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubt/anaconda3/envs/face/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 59, in <module>
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 349, in run
          self.run_command("build")
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-mzvdeyxd/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyreaper/creaper.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyreaper
Failed to build pyreaper
ERROR: Could not build wheels for pyreaper, which is required to install pyproject.toml-based projects

```

**Comment by r9y9** [comment]
Please try the latest master that includes https://github.com/r9y9/pyreaper/commit/c5563f35fe891b149369862870e26285dd22926e

I'll make a new release if it works

**Comment by Ting011** [comment]
> Please try the latest master that includes [c5563f3](https://github.com/r9y9/pyreaper/commit/c5563f35fe891b149369862870e26285dd22926e)
> 
> I'll make a new release if it works

Thank you for your reply.
I have download the lastest master and use ```setup.py ``` and ```MANIFEST.in``` in it.

``` 
pip install .
```
Seems it failed with error log below:
```
Requirement already satisfied: numpy>=1.8.0 in /home/ubt/anaconda3/envs/face/lib/python3.8/site-packages (from pyreaper==0.0.10.dev0) (1.24.4)
Building wheels for collected packages: pyreaper
  Building wheel for pyreaper (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyreaper (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      []
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-38
      creating build/lib.linux-aarch64-cpython-38/pyreaper
      copying pyreaper/__init__.py -> build/lib.linux-aarch64-cpython-38/pyreaper
      running build_ext
      Compiling pyreaper/creaper.pyx because it changed.
      [1/1] Cythonizing pyreaper/creaper.pyx
      building 'pyreaper.creaper' extension
      creating build/temp.linux-aarch64-cpython-38
      creating build/temp.linux-aarch64-cpython-38/pyreaper
      gcc -pthread -B /home/ubt/anaconda3/envs/face/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/numpy/core/include -I/home/ubt/pyreaper/pyreaper/lib/REAPER -I/home/ubt/anaconda3/envs/face/include/python3.8 -c pyreaper/creaper.cpp -o build/temp.linux-aarch64-cpython-38/pyreaper/creaper.o
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from /tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940,
                       from /tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from pyreaper/creaper.cpp:1120:
      /tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      pyreaper/creaper.cpp:1132:10: fatal error: core/track.h: No such file or directory
       1132 | #include "core/track.h"
            |          ^~~~~~~~~~~~~~
      compilation terminated.
      <string>:18: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      /tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/setuptools/dist.py:508: InformationOnly: Normalizing '0.0.10-dev' to '0.0.10.dev0'
        self.metadata.version = self._normalize_version(
      /tmp/pip-build-env-b22ff37l/overlay/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/ubt/pyreaper/pyreaper/pyreaper/creaper.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyreaper
Failed to build pyreaper
ERROR: Could not build wheels for pyreaper, which is required to install pyproject.toml-based projects

```

**Comment by r9y9** [comment]
Can you try the following command?

```
git submodule update --init  --recursive
```

and then run 
```
pip install .
```

**Comment by Ting011** [comment]
> 

It works. Thank you for your help!

**Comment by r9y9** [comment]
https://github.com/r9y9/pyreaper/releases/tag/v0.0.10 tagged a new release. `pip install -U pyreaper` should also work now.

**Comment by WhiteTeaDragon** [comment]
For anyone who stumbles across this problem while trying to install a particular version of pyreaper: uninstalling Cython might also help: `pip uninstall Cython`
