### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by fanpengustc** [r9y9/pyreaper#4]
the pyreaper seems memory leak
when i run the pyreaper on large wav files, the memory(64GB) always exhausted!!!

**Comment by r9y9** [comment]
Thank you for the report. I quickly looked into pyreaper code but seems there's no memory leak. I'm wondering this is caused by REAPER intenal.

**Comment by fanpengustc** [comment]
Maybe!  Thanks for your anwser!

**Comment by r9y9** [comment]
Okay, found memory leaks. Will fix shortly.

```
./reaper -i ~/Dropbox/data/test.wav                                                                                                                                                                                 1   master 
Residual symmetry: P:775.976318  N:682.635132  MEAN:-0.694277
Inverting signal

=================================================================
==20034==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3905216 byte(s) in 122038 object(s) allocated from:
    #0 0x527118 in operator new(unsigned long) /home/ryuichi/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:92
    #1 0x53bea5 in EpochTracker::CreatePeriodLattice() /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker/epoch_tracker.cc:837:29
    #2 0x53b098 in EpochTracker::TrackEpochs() /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker/epoch_tracker.cc:785:3
    #3 0x52c609 in ComputeEpochsAndF0(EpochTracker&, float, float, Track**, Track**, Track**) /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker_main.cc:130:23
    #4 0x52d40d in main /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker_main.cc:227:8
    #5 0x7f3ae82c882f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291

Direct leak of 91232 byte(s) in 2851 object(s) allocated from:
    #0 0x527118 in operator new(unsigned long) /home/ryuichi/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:92
    #1 0x53b914 in EpochTracker::CreatePeriodLattice() /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker/epoch_tracker.cc:809:26
    #2 0x53b098 in EpochTracker::TrackEpochs() /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker/epoch_tracker.cc:785:3
    #3 0x52c609 in ComputeEpochsAndF0(EpochTracker&, float, float, Track**, Track**, Track**) /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker_main.cc:130:23
    #4 0x52d40d in main /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker_main.cc:227:8
    #5 0x7f3ae82c882f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291

Direct leak of 65472 byte(s) in 2046 object(s) allocated from:
    #0 0x527118 in operator new(unsigned long) /home/ryuichi/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:92
    #1 0x53db06 in EpochTracker::CreatePeriodLattice() /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker/epoch_tracker.cc:928:30
    #2 0x53b098 in EpochTracker::TrackEpochs() /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker/epoch_tracker.cc:785:3
    #3 0x52c609 in ComputeEpochsAndF0(EpochTracker&, float, float, Track**, Track**, Track**) /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker_main.cc:130:23
    #4 0x52d40d in main /home/ryuichi/Dropbox/sp/REAPER/epoch_tracker_main.cc:227:8
    #5 0x7f3ae82c882f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: 4061920 byte(s) leaked in 126935 allocation(s).
```

**Comment by r9y9** [comment]
This should be fixed now. Could you check if it works with latest master?

```
https://github.com/r9y9/pyreaper
cd pyreaper
git submodule update --recursive --init 
python setup.py develop
```

**Comment by fanpengustc** [comment]
ok i will test it

**Comment by fanpengustc** [comment]
Yeah! The bug seems fixed now ,the memory consumption is normal by my large amount of wav files  test. Thanks for your help!

**Comment by r9y9** [comment]
Thank you for the confirmation!
